In [2]:
import pandas as pd
import numpy as np
import geopandas as gpd
from matplotlib import pyplot as plt
import geopandas as gpd

In [3]:
countries_1715 = gpd.read_file('world_1715.json')
countries_1715['YEAR']='1715'

In [4]:
countries_1783 = gpd.read_file('world_1783.json')
countries_1783['YEAR']='1783'

In [5]:
countries_1800 = gpd.read_file('world_1800.json')
countries_1800['YEAR']='1800'

In [6]:
countries_1815 = gpd.read_file('world_1815.json')
countries_1815['YEAR']='1815'

In [7]:
countries_1880 = gpd.read_file('world_1880.json')
countries_1880['YEAR']='1880'

In [8]:
countries_1914 = gpd.read_file('world_1914.json')
countries_1914['YEAR']='1914'

In [9]:
countries_1920 = gpd.read_file('world_1920.json')
countries_1920['YEAR']='1920'

In [10]:
countries_1938 = gpd.read_file('world_1938.json')
countries_1938['YEAR']='1938'

In [11]:
countries_1945 = gpd.read_file('world_1945.json')
countries_1945['YEAR']='1945'

In [12]:
countries_1960 = gpd.read_file('world_1960.json')
countries_1960['YEAR']='1960'

In [13]:
countries_1994 = gpd.read_file('world_1994.json')
countries_1994['YEAR']='1994'

In [14]:
frames = [countries_1715, countries_1783, countries_1800, countries_1815, countries_1880, countries_1914, countries_1920, countries_1938, countries_1945, countries_1960, countries_1994]

In [15]:
result = pd.concat(frames)

In [16]:
result.head()

,NAME,ABBREVN,SUBJECTO,BORDERPRECISION,PARTOF,geometry,YEAR,FIPS_CO,WB_CNTR,color_id,FIPS_CODE,WB_CNTRY,AREA,BORDERI,BORDER_
0,Luxembourg,Luxembourg,Luxembourg,3,Luxembourg,"MULTIPOLYGON (((5.82350 49.50711, 5.88440 49.6...",1715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ottoman Empire,Ottoman Emp.,Ottoman Empire,3,Ottoman Empire,"MULTIPOLYGON (((23.24241 39.04412, 23.40966 38...",1715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,None,None,None,3,None,"MULTIPOLYGON (((120.62239 21.92520, 120.57658 ...",1715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Cuba (Spain),Cuba (Spain),Spain,3,Cuba (Spain),"MULTIPOLYGON (((-82.17723 22.36591, -82.04057 ...",1715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Haiti,Haiti,Haiti,3,Haiti,"MULTIPOLYGON (((-71.77706 19.77101, -71.76923 ...",1715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
result_new = result.drop(['FIPS_CO', 'WB_CNTR', 'color_id', 'FIPS_CODE', 'WB_CNTRY', 'AREA', 'BORDERI', 'BORDER_'], axis=1)

In [18]:
result_new

,NAME,ABBREVN,SUBJECTO,BORDERPRECISION,PARTOF,geometry,YEAR
0,Luxembourg,Luxembourg,Luxembourg,3,Luxembourg,"MULTIPOLYGON (((5.82350 49.50711, 5.88440 49.6...",1715
1,Ottoman Empire,Ottoman Emp.,Ottoman Empire,3,Ottoman Empire,"MULTIPOLYGON (((23.24241 39.04412, 23.40966 38...",1715
2,None,None,None,3,None,"MULTIPOLYGON (((120.62239 21.92520, 120.57658 ...",1715
3,Cuba (Spain),Cuba (Spain),Spain,3,Cuba (Spain),"MULTIPOLYGON (((-82.17723 22.36591, -82.04057 ...",1715
4,Haiti,Haiti,Haiti,3,Haiti,"MULTIPOLYGON (((-71.77706 19.77101, -71.76923 ...",1715
...,...,...,...,...,...,...,...
227,None,None,None,3,None,"MULTIPOLYGON (((128.95108 27.67583, 128.94470 ...",1994
228,None,None,None,3,None,"MULTIPOLYGON (((128.60913 27.35889, 128.56580 ...",1994
229,None,None,None,3,None,"MULTIPOLYGON (((129.99219 28.28167, 129.98691 ...",1994
230,None,None,None,3,None,"MULTIPOLYGON (((129.33609 28.07528, 129.32941 ...",1994
231,None,None,None,3,None,"MULTIPOLYGON (((129.73303 29.60972, 129.72220 ...",1994

In [19]:
countries_allyears = result_new

In [20]:
# countries_to_keep = ['Poland', 'Polish–Lithuanian Commonwealth', 'Bylarus', 'Byelarus', 'Belarus', 'Germany (Soviet)', 'Germany (USA)', 'Germany (France)', 'Germany (UK)', 'Russia', 'Lithuania', 'USSR', 'White Russia', 'Ukraine', 'Hungary', 'Austro-Hungarian Empire', 'Austria', 'Austrian Empire', 'Prussia', 'East Prussia', 'Czechoslovakia', 'Germany', 'German Empire', 'Latvia', 'Moldova', 'Russian Empire', 'East Germany', 'West Germany', 'Estonia', 'Czech Republic', 'Slovakia', 'Habsburg Austria']
#test = countries_allyears.NAME.isin(countries_to_keep)

In [21]:
countries_to_keep = ['Poland', 'Polish–Lithuanian Commonwealth', 'Bylarus', 'Byelarus', 'Belarus', 'Russia', 'USSR', 'White Russia', 'Russian Empire']
test = countries_allyears.NAME.isin(countries_to_keep)

In [22]:
test = countries_allyears[countries_allyears.NAME.isin(countries_to_keep)]

In [23]:
test

,NAME,ABBREVN,SUBJECTO,BORDERPRECISION,PARTOF,geometry,YEAR
84,Polish–Lithuanian Commonwealth,Polish–Lithuanian Commonwealth,Polish–Lithuanian Commonwealth,3,Polish–Lithuanian Commonwealth,"MULTIPOLYGON (((29.51795 58.07518, 29.99517 58...",1715
302,Russian Empire,Russia,Russian Empire,3,Russian Empire,"MULTIPOLYGON (((150.80276 46.44305, 150.79852 ...",1715
143,Poland,Poland,Poland,3,Poland,"MULTIPOLYGON (((29.01060 47.55391, 28.90822 47...",1783
144,Russian Empire,Russia,Russian Empire,3,Russian Empire,"MULTIPOLYGON (((28.52151 60.62326, 28.55972 60...",1783
151,Russia,Russia,Russia,3,Russia,"MULTIPOLYGON (((146.20554 43.48110, 146.16885 ...",1783
145,Russia,Russia,Russia,3,Russia,"MULTIPOLYGON (((146.20554 43.48110, 146.16885 ...",1800
618,Russian Empire,Russia,Russian Empire,3,Russian Empire,"MULTIPOLYGON (((54.66363 73.47200, 54.47871 73...",1800
144,Russian Empire,Russia,Russian Empire,3,Russian Empire,"MULTIPOLYGON (((-168.50734 53.42886, -168.3559...",1815
148,Russia,Russia,Russia,3,Russia,"MULTIPOLYGON (((146.20554 43.48110, 146.16885 ...",1815
126,Russian Empire,Russian Empire,Russian Empire,3,Russian Empire,"MULTIPOLYGON (((-168.04072 53.30943, -168.3743...",1880
108,Russia,Russia,Russia,3,Russia,"MULTIPOLYGON (((137.60194 56.24035, 137.22909 ...",1914
115,White Russia,White Russia,White Russia,3,White Russia,"MULTIPOLYGON (((27.58047 55.78118, 27.61130 55...",1920
116,Poland,Poland,Poland,3,Poland,"MULTIPOLYGON (((22.24723 49.19489, 22.19643 49...",1920
126,USSR,USSR,USSR,3,USSR,"MULTIPOLYGON (((118.44889 55.05905, 114.85976 ...",1920
131,Poland,Poland,Poland,3,Poland,"MULTIPOLYGON (((27.50473 54.70284, 26.71505 54...",1938
147,USSR,USSR,USSR,3,USSR,"MULTIPOLYGON (((31.40830 62.79197, 31.33593 62...",1938
101,Poland,Poland,Poland,3,Poland,"MULTIPOLYGON (((14.06995 53.91777, 14.17417 53...",1945
138,USSR,USSR,USSR,3,USSR,"MULTIPOLYGON (((143.14329 52.51124, 143.03341 ...",1945
103,Poland,Poland,Poland,3,Poland,"MULTIPOLYGON (((14.06995 53.91777, 14.17417 53...",1960
142,USSR,USSR,USSR,3,USSR,"MULTIPOLYGON (((143.13887 52.85625, 143.14329 ...",1960
57,Byelarus,Byelarus,Byelarus,3,Byelarus,"MULTIPOLYGON (((23.53050 53.91629, 23.57206 53...",1994
123,Poland,Poland,Poland,3,Poland,"MULTIPOLYGON (((22.57044 49.06668, 22.19643 49...",1994
155,Russia,Russia,Russia,3,Russia,"MULTIPOLYGON (((143.03341 52.31219, 142.94488 ...",1994
161,Russia,Russia,Russia,3,Russia,"MULTIPOLYGON (((146.20554 43.48110, 146.16885 ...",1994

In [24]:
easternEurope = test

In [25]:
easternEurope.to_file("easternEurope.geojson", driver='GeoJSON')